baseurl = "https://danielczarnievicz.netlify.app"
title = "Daniel Czarnievicz"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  style = "blue"
  description = "Me and my data vizs"
  copyright = "&copy;2020 Daniel Czarnievicz"
  sidebarAbout = [
    "I am an economist and data scientist with over 10 years of experience. I have worked both in academia and in the private sector.",
    "I currently work as a Product Analyst at PedidosYa, one of the largest online food delivery companies in Latin America with presence in 8 countries."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  twitter = "https://twitter.com/daczarne"
  linkedin = "https://www.linkedin.com/in/danielczarnievicz/"
  stackoverflow = "https://stackoverflow.com/users/5908830/daniel"
  github = "https://github.com/daczarne"
  whatsapp = "https://wa.me/59891787420"
